buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 2376878
    empty: 4475893
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our Code of Conduct
          messages:
            - "Our Code of Conduct can be found at https://ropensci.org"
      - seeking_reviewers:
          command: seeking reviewers
          description: Switch to "seeking reviewers"
          template_file: badge.md
          remove_labels:
            - 1/editor-checks
          add_labels:
            - 2/seeking-reviewer(s)
          only: editors
    assign_reviewer_n:
      only: editors
      if:
        role_assigned: editor
    remove_reviewer_n:
      only: editors
      no_reviewer_text: "TBD"
    assign_editor:
      only: editors
      add_labels:
        - 1/editor-checks
    remove_editor:
      only: editors
      no_editor_text: "TBD"
